# Site settings
title: SO RELAXED MASSAGE
description: Massage Website
kicker: DEEP TISSUE ~ SWEDISH ~ OIL MASSAGE
keywords: Massage, Edmond, Store
address1: 1141 W 15th St,
address2: Edmond, OK 73013
author: Dake Zhang
baseurl: "" # the subpath of your site, e.g. /blog/
url: "/Jekyll/" # the base hostname & protocol for your site
